package mx.com.garnet.persistence.entities;



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEspecie generated by hbm2java
 */
@Entity
@Table(name = "Cat_Especie", catalog = "garnet")
public class CatEspecie implements java.io.Serializable {

	private Integer idEspecie;
	private String nombre;
	private Set<DatPaciente> datPacientes = new HashSet<DatPaciente>(0);

	public CatEspecie() {
	}

	public CatEspecie(String nombre) {
		this.nombre = nombre;
	}

	public CatEspecie(String nombre, Set<DatPaciente> datPacientes) {
		this.nombre = nombre;
		this.datPacientes = datPacientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEspecie", unique = true, nullable = false)
	public Integer getIdEspecie() {
		return this.idEspecie;
	}

	public void setIdEspecie(Integer idEspecie) {
		this.idEspecie = idEspecie;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catEspecie")
	public Set<DatPaciente> getDatPacientes() {
		return this.datPacientes;
	}

	public void setDatPacientes(Set<DatPaciente> datPacientes) {
		this.datPacientes = datPacientes;
	}

}
