package mx.com.garnet.persistence.entities;
// Generated 28 feb 2019 19:36:59 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CatPreguntaSecreta generated by hbm2java
 */
@Entity
@Table(name = "Cat_Pregunta_Secreta", schema = "dbo", catalog = "Xocolatl")
public class CatPreguntaSecreta implements java.io.Serializable {

	private Integer idPreguntaSecreta;
	private String preguntaSecreta;


	public CatPreguntaSecreta() {
	}

	public CatPreguntaSecreta(String preguntaSecreta) {
		this.preguntaSecreta = preguntaSecreta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdPreguntaSecreta", unique = true, nullable = false)
	public Integer getIdPreguntaSecreta() {
		return this.idPreguntaSecreta;
	}

	public void setIdPreguntaSecreta(Integer idPreguntaSecreta) {
		this.idPreguntaSecreta = idPreguntaSecreta;
	}

	@Column(name = "PreguntaSecreta")
	public String getPreguntaSecreta() {
		return this.preguntaSecreta;
	}

	public void setPreguntaSecreta(String preguntaSecreta) {
		this.preguntaSecreta = preguntaSecreta;
	}

}
