package mx.com.garnet.persistence.entities;
<<<<<<< HEAD
// Generated 23 jul 2019 12:19:15 by Hibernate Tools 5.1.10.Final
=======
// Generated 23/07/2019 12:10:14 PM by Hibernate Tools 5.1.10.Final
>>>>>>> master

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatMedico generated by hbm2java
 */
@Entity
@Table(name = "Dat_Medico", catalog = "garnet")
public class DatMedico implements java.io.Serializable {

	private Integer idMedico;
	private CatEspecialidad catEspecialidad;
	private String nombre;
	private String cedula;
	private String horario;
	private Date fechaIngreso;
	private boolean status;
	private Set<DatConsulta> datConsultas = new HashSet<DatConsulta>(0);

	public DatMedico() {
	}

	public DatMedico(CatEspecialidad catEspecialidad, String nombre, String cedula, String horario, Date fechaIngreso,
			boolean status) {
		this.catEspecialidad = catEspecialidad;
		this.nombre = nombre;
		this.cedula = cedula;
		this.horario = horario;
		this.fechaIngreso = fechaIngreso;
		this.status = status;
	}

	public DatMedico(CatEspecialidad catEspecialidad, String nombre, String cedula, String horario, Date fechaIngreso,
			boolean status, Set<DatConsulta> datConsultas) {
		this.catEspecialidad = catEspecialidad;
		this.nombre = nombre;
		this.cedula = cedula;
		this.horario = horario;
		this.fechaIngreso = fechaIngreso;
		this.status = status;
		this.datConsultas = datConsultas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idMedico", unique = true, nullable = false)
	public Integer getIdMedico() {
		return this.idMedico;
	}

	public void setIdMedico(Integer idMedico) {
		this.idMedico = idMedico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEspecialidad", nullable = false)
	public CatEspecialidad getCatEspecialidad() {
		return this.catEspecialidad;
	}

	public void setCatEspecialidad(CatEspecialidad catEspecialidad) {
		this.catEspecialidad = catEspecialidad;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "cedula", nullable = false, length = 15)
	public String getCedula() {
		return this.cedula;
	}

	public void setCedula(String cedula) {
		this.cedula = cedula;
	}

	@Column(name = "horario", nullable = false, length = 1)
	public String getHorario() {
		return this.horario;
	}

	public void setHorario(String horario) {
		this.horario = horario;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaIngreso", nullable = false, length = 10)
	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datMedico")
	public Set<DatConsulta> getDatConsultas() {
		return this.datConsultas;
	}

	public void setDatConsultas(Set<DatConsulta> datConsultas) {
		this.datConsultas = datConsultas;
	}

}
