package mx.com.garnet.persistence.entities;
//<<<<<<< HEAD
// Generated 23 jul 2019 12:19:15 by Hibernate Tools 5.1.10.Final
//=======
// Generated 23/07/2019 12:10:14 PM by Hibernate Tools 5.1.10.Final
//>>>>>>> master

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatPaciente generated by hbm2java
 */
@Entity
@Table(name = "Dat_Paciente", catalog = "garnet")
public class DatPaciente implements java.io.Serializable {

	private Integer idPaciente;
	private CatEspecie catEspecie;
	private DatDueno datDueno;
	private String nombre;
	private String raza;
	private Date fechaNacimiento;
	private boolean status;
	private String comentarios;
	private String sexo;
	private String foto;
	private Date fechaAlta;
	private String numeroRegistro;
	private Set<DatConsulta> datConsultas = new HashSet<DatConsulta>(0);

	public DatPaciente() {
	}

	public DatPaciente(CatEspecie catEspecie, DatDueno datDueno, String nombre, Date fechaNacimiento, boolean status,
			String sexo, Date fechaAlta, String numeroRegistro) {
		this.catEspecie = catEspecie;
		this.datDueno = datDueno;
		this.nombre = nombre;
		this.fechaNacimiento = fechaNacimiento;
		this.status = status;
		this.sexo = sexo;
		this.fechaAlta = fechaAlta;
		this.numeroRegistro = numeroRegistro;
	}

	public DatPaciente(CatEspecie catEspecie, DatDueno datDueno, String nombre, String raza, Date fechaNacimiento,
			boolean status, String comentarios, String sexo, String foto, Date fechaAlta, String numeroRegistro,
			Set<DatConsulta> datConsultas) {
		this.catEspecie = catEspecie;
		this.datDueno = datDueno;
		this.nombre = nombre;
		this.raza = raza;
		this.fechaNacimiento = fechaNacimiento;
		this.status = status;
		this.comentarios = comentarios;
		this.sexo = sexo;
		this.foto = foto;
		this.fechaAlta = fechaAlta;
		this.numeroRegistro = numeroRegistro;
		this.datConsultas = datConsultas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPaciente", unique = true, nullable = false)
	public Integer getIdPaciente() {
		return this.idPaciente;
	}

	public void setIdPaciente(Integer idPaciente) {
		this.idPaciente = idPaciente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idEspecie", nullable = false)
	public CatEspecie getCatEspecie() {
		return this.catEspecie;
	}

	public void setCatEspecie(CatEspecie catEspecie) {
		this.catEspecie = catEspecie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDueno", nullable = false)
	public DatDueno getDatDueno() {
		return this.datDueno;
	}

	public void setDatDueno(DatDueno datDueno) {
		this.datDueno = datDueno;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "raza", length = 45)
	public String getRaza() {
		return this.raza;
	}

	public void setRaza(String raza) {
		this.raza = raza;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", nullable = false, length = 10)
	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "comentarios", length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "foto", length = 100)
	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaAlta", nullable = false, length = 19)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "numeroRegistro", nullable = false, length = 10)
	public String getNumeroRegistro() {
		return this.numeroRegistro;
	}

	public void setNumeroRegistro(String numeroRegistro) {
		this.numeroRegistro = numeroRegistro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "datPaciente")
	public Set<DatConsulta> getDatConsultas() {
		return this.datConsultas;
	}

	public void setDatConsultas(Set<DatConsulta> datConsultas) {
		this.datConsultas = datConsultas;
	}

}
